---
- name: Shutdown a VM
  hosts: localhost
  tasks:
    - name: Stop ec2 instance
      amazon.aws.ec2_instance:
        filters:
          "tag:Name": "{{ item }}"
        region: "{{ aws_region }}"
        state: "stopped"
      loop: "{{ vm_names }}"
      

