---
- name: Shutdown a VM
  hosts: localhost
  tasks:
    - name: start an instance and Add EBS volume from a snapshot
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        region: "{{ aws_region }}"
        state: "stopped"
      loop: "{{ vm_names }}"
      

